export const LOG_IN = 'SET_IS_ADMIN_LOGIN';
export const ADMIN_MODULE_ID = 'SET_ADMIN_MODULE_ID';
export const ADMIN_MENU_OPEN = 'SET_IS_ADMIN_MENU_OPEN';
export const SET_PORTAL_STATUS = 'SET_PORTAL_ON';
export const SET_PORTAL_ID = 'SET_PORTAL_ID';
export const SET_ADMIN_PORTAL_TARGET = 'SET_ADMIN_PORTAL_TARGET';